name: 'Setup Project'
description: 'Setup pnpm, Node.js, and install dependencies'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@9fd676a19091d4595eefd76e4bd31c97133911f1 # v4.2.0
    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
    - run: pnpm install --frozen-lockfile
      shell: bash
