name: 'Combine JUnit Reports'
description: 'Downloads, combines, and uploads JUnit XML reports'
inputs:
  artifact-pattern:
    description: 'Pattern to match artifact names (e.g. "junit-*")'
    required: true
  output-name:
    description: 'Name of the output artifact'
    required: true
runs:
  using: "composite"
  steps:
    - name: Download all JUnit artifacts
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        pattern: ${{ inputs.artifact-pattern }}
        path: junit-results/
        merge-multiple: true
    - name: Combine JUnit reports
      shell: bash
      run: |
        mkdir -p combined-junit
        # Check if any XML files exist
        if [ -d "junit-results" ] && compgen -G "junit-results/*.xml" > /dev/null; then
          echo '<?xml version="1.0" encoding="UTF-8"?>' > combined-junit/junit-combined.xml
          echo '<testsuites>' >> combined-junit/junit-combined.xml
          for file in junit-results/*.xml; do
            # Extract testsuite elements (skip XML declaration and testsuites wrapper)
            sed -n '/<testsuite[> ]/,/<\/testsuite>/p' "$file" >> combined-junit/junit-combined.xml
          done
          echo '</testsuites>' >> combined-junit/junit-combined.xml
          echo "✅ Combined JUnit reports successfully"
          echo "Reports found:"
          ls -la junit-results/
        else
          echo "⚠️ No JUnit reports found to combine"
        fi
    - name: Upload combined JUnit results
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.4
      if: always()
      with:
        name: ${{ inputs.output-name }}
        path: combined-junit/
        retention-days: 7
